openapi: 3.0.0
info:
  title: Maintenance API
  description: API for managing maintenance requests, logs, and room details.
  version: 1.0.0

paths:
  /maintenanceRequests:
    post:
      summary: Create a new maintenance request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceRequest'
      responses:
        '201':
          description: Maintenance request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRequestResponse'

    get:
      summary: Get all maintenance requests
      responses:
        '200':
          description: List of maintenance requests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MaintenanceRequest'

  /maintenanceRequests/{requestId}:
    get:
      summary: Get details of a specific maintenance request
      parameters:
        - in: path
          name: requestId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Maintenance request details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceRequest'

    put:
      summary: Update a specific maintenance request
      parameters:
        - in: path
          name: requestId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceRequest'
      responses:
        '200':
          description: Maintenance request updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

    delete:
      summary: Delete a specific maintenance request
      parameters:
        - in: path
          name: requestId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Maintenance request deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

components:
  schemas:
    MaintenanceRequest:
      type: object
      properties:
        roomId:
          type: string
          description: Id identifier for the room where the issue was reported
        roomName:
          type: string
          description: Name identifier for the room where the issue was reported
        userId:
          type: string
          description: Unique identifier for the user who reported the issue
        issueType:
          type: string
          description: The type of issue reported (e.g., "Electrical", "Plumbing")
        description:
          type: string
          description: Detailed description of the issue
        status:
          type: string
          description: Current status of the request (e.g., "Scheduled", "In Progress", "Completed")
        createdAt:
          type: string
          format: date-time
          description: Date and time when the request was created
        timestamp:
          type: string
          format: date-time
          description: Date and time when the request will be completed
        assignedTo:
          type: string
          description: Identifier for the staff member assigned to the request

    CreateRequestResponse:
      type: object
      properties:
        requestId:
          type: string
          description: Unique identifier for the created request
        message:
          type: string
          description: Confirmation message


    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Confirmation message
