openapi: 3.0.0
info:
  title: Notification API
  description: API for managing user notifications
  version: 1.0.0
servers:
  - url: https://campus-infrastructure-management.azurewebsites.net/api/

paths:
  /users/{userId}/notifications:
    get:
      summary: Get all notifications for a user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user
      responses:
        '200':
          description: A list of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    message:
                      type: string
                    sendAt:
                      type: string
                      format: date-time
                    createdAt:
                      type: string
                      format: date-time
                    status:
                      type: string
        '500':
          description: Error getting notifications

    post:
      summary: Create a new notification for a user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: reminder
                message:
                  type: string
                  example: "Your booking is confirmed."
                sendAt:
                  type: string
                  format: date-time
                  example: "2024-05-01T10:00:00Z"
      responses:
        '201':
          description: Notification created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  notificationId:
                    type: string
                  message:
                    type: string
                    example: "Notification created successfully."
        '500':
          description: Error creating notification

  /users/{userId}/notifications/{notificationId}:
    get:
      summary: Get a specific notification by notificationId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user
        - in: path
          name: notificationId
          required: true
          schema:
            type: string
          description: ID of the notification
      responses:
        '200':
          description: Notification details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  message:
                    type: string
                  sendAt:
                    type: string
                    format: date-time
                  createdAt:
                    type: string
                    format: date-time
                  status:
                    type: string
        '404':
          description: Notification not found
        '500':
          description: Error getting notification

    put:
      summary: Update a notification by notificationId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user
        - in: path
          name: notificationId
          required: true
          schema:
            type: string
          description: ID of the notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: reminder
                message:
                  type: string
                  example: "Your booking is confirmed."
                sendAt:
                  type: string
                  format: date-time
                status:
                  type: string
                  example: pending
      responses:
        '200':
          description: Notification updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Notification updated successfully."
        '500':
          description: Error updating notification

    delete:
      summary: Delete a notification by notificationId
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user
        - in: path
          name: notificationId
          required: true
          schema:
            type: string
          description: ID of the notification
      responses:
        '200':
          description: Notification deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Notification deleted successfully."
        '500':
          description: Error deleting notification
